
package com.Partner;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "BestellServiceException", targetNamespace = "http://service.sw.othr.de/")
public class BestellServiceException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BestellServiceException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BestellServiceException_Exception(String message, BestellServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public BestellServiceException_Exception(String message, BestellServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.Partner.BestellServiceException
     */
    public BestellServiceException getFaultInfo() {
        return faultInfo;
    }

}
