
package com.Partner;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BestellService", targetNamespace = "http://service.sw.othr.de/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BestellService {


    /**
     * 
     * @param bestellung
     * @param kunde
     * @return
     *     returns com.Partner.Kunde
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bestellungAufgeben", targetNamespace = "http://service.sw.othr.de/", className = "com.Partner.BestellungAufgeben")
    @ResponseWrapper(localName = "bestellungAufgebenResponse", targetNamespace = "http://service.sw.othr.de/", className = "com.Partner.BestellungAufgebenResponse")
    public Kunde bestellungAufgeben(
        @WebParam(name = "kunde", targetNamespace = "")
        Kunde kunde,
        @WebParam(name = "bestellung", targetNamespace = "")
        Bestellung bestellung);

}
