
package com.Partner;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BestellServiceService", targetNamespace = "http://service.sw.othr.de/", wsdlLocation = "http://im-lamport:8080/Mich_Fotoshop-0.1/BestellService?wsdl")
public class BestellServiceService
    extends Service
{

    private final static URL BESTELLSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException BESTELLSERVICESERVICE_EXCEPTION;
    private final static QName BESTELLSERVICESERVICE_QNAME = new QName("http://service.sw.othr.de/", "BestellServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://im-lamport:8080/Mich_Fotoshop-0.1/BestellService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BESTELLSERVICESERVICE_WSDL_LOCATION = url;
        BESTELLSERVICESERVICE_EXCEPTION = e;
    }

    public BestellServiceService() {
        super(__getWsdlLocation(), BESTELLSERVICESERVICE_QNAME);
    }

    public BestellServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BESTELLSERVICESERVICE_QNAME, features);
    }

    public BestellServiceService(URL wsdlLocation) {
        super(wsdlLocation, BESTELLSERVICESERVICE_QNAME);
    }

    public BestellServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BESTELLSERVICESERVICE_QNAME, features);
    }

    public BestellServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BestellServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BestellService
     */
    @WebEndpoint(name = "BestellServicePort")
    public BestellService getBestellServicePort() {
        return super.getPort(new QName("http://service.sw.othr.de/", "BestellServicePort"), BestellService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BestellService
     */
    @WebEndpoint(name = "BestellServicePort")
    public BestellService getBestellServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.sw.othr.de/", "BestellServicePort"), BestellService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BESTELLSERVICESERVICE_EXCEPTION!= null) {
            throw BESTELLSERVICESERVICE_EXCEPTION;
        }
        return BESTELLSERVICESERVICE_WSDL_LOCATION;
    }

}
